# Generated by Django 2.0.6 on 2018-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0009_auto_20180314_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='object_repr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='user_pk_as_string',
            field=models.TextField(blank=True, default=None, help_text='String version of the user pk', null=True),
        ),
    ]
